"""
WorkoutMetadata value object for workout provenance and tracking.

Part of AMA-389: Define canonical Workout domain model
"""

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, HttpUrl


class WorkoutSource(str, Enum):
    """
    Sources from which a workout can originate.

    - AI: Generated by AI from voice/text input
    - YOUTUBE: Imported from YouTube video
    - IMPORT: Imported from file (CSV, Excel, etc.)
    - MANUAL: Manually created by user
    - TEMPLATE: Created from a template
    - COACH: Assigned by a coach
    """

    AI = "ai"
    YOUTUBE = "youtube"
    IMPORT = "import"
    MANUAL = "manual"
    TEMPLATE = "template"
    COACH = "coach"


class WorkoutMetadata(BaseModel):
    """
    Value object containing workout provenance and tracking metadata.

    This includes information about where the workout came from,
    what platform it's targeted for, and export/sync status.

    Examples:
        >>> metadata = WorkoutMetadata(
        ...     sources=[WorkoutSource.AI],
        ...     platform="ios_companion"
        ... )

        >>> metadata = WorkoutMetadata(
        ...     sources=[WorkoutSource.YOUTUBE],
        ...     source_url="https://youtube.com/watch?v=...",
        ...     platform="garmin"
        ... )
    """

    # Source tracking
    sources: List[WorkoutSource] = Field(
        default_factory=list,
        description="Origins of this workout (e.g., AI, YouTube, import)",
    )
    source_url: Optional[str] = Field(
        default=None,
        description="URL from which the workout was imported (if applicable)",
    )

    # Target platform
    platform: Optional[str] = Field(
        default=None,
        description="Target device/platform (e.g., 'garmin', 'apple', 'ios_companion')",
    )

    # Timestamps
    created_at: Optional[datetime] = Field(
        default=None, description="When the workout was created"
    )
    updated_at: Optional[datetime] = Field(
        default=None, description="When the workout was last modified"
    )

    # Export tracking
    is_exported: bool = Field(
        default=False, description="Whether the workout has been exported to a device"
    )
    exported_at: Optional[datetime] = Field(
        default=None, description="When the workout was exported"
    )
    exported_to_device: Optional[str] = Field(
        default=None, description="Device identifier the workout was exported to"
    )

    # Sync tracking (for iOS Companion)
    ios_companion_synced_at: Optional[datetime] = Field(
        default=None, description="When the workout was synced to iOS Companion app"
    )

    # Workout type for categorization (strength, cardio, hiit, circuit, etc.)
    workout_type: Optional[str] = Field(
        default=None, description="Workout type for categorization (e.g., 'strength', 'cardio', 'hiit')"
    )

    @property
    def is_ai_generated(self) -> bool:
        """Check if this workout was AI-generated."""
        return WorkoutSource.AI in self.sources

    @property
    def is_imported(self) -> bool:
        """Check if this workout was imported from an external source."""
        return WorkoutSource.YOUTUBE in self.sources or WorkoutSource.IMPORT in self.sources

    @property
    def has_source_url(self) -> bool:
        """Check if this workout has a source URL."""
        return self.source_url is not None

    @property
    def is_synced(self) -> bool:
        """Check if this workout has been synced/exported."""
        return self.is_exported or self.ios_companion_synced_at is not None

    def __str__(self) -> str:
        """Human-readable string representation."""
        parts = []

        if self.sources:
            sources_str = ", ".join(s.value for s in self.sources)
            parts.append(f"sources=[{sources_str}]")

        if self.platform:
            parts.append(f"platform={self.platform}")

        if self.is_exported:
            parts.append("exported")

        return f"WorkoutMetadata({', '.join(parts)})" if parts else "WorkoutMetadata()"

    model_config = {
        "frozen": True,  # Make immutable (value object semantics)
        "json_schema_extra": {
            "examples": [
                {
                    "sources": ["ai"],
                    "platform": "ios_companion",
                    "created_at": "2025-01-15T10:00:00Z",
                },
                {
                    "sources": ["youtube"],
                    "source_url": "https://youtube.com/watch?v=abc123",
                    "platform": "garmin",
                    "is_exported": True,
                    "exported_at": "2025-01-15T12:00:00Z",
                },
            ]
        },
    }
